#! /bin/bash
#PBS -N run4_repeated
#PBS -P InfoDynFuncStruct
#PBS -l select=1:ncpus=32:mem=32GB
#PBS -l walltime=04:00:00
#PBS -M lnov6504@uni.sydney.edu.au
#PBS -m abe
#PBS -q defaultQ
module load java
module load python/3.5.1
source /project/RDS-FEI-InfoDynFuncStruct-RW/Leo/idtxl_env/bin/activate
python_script_path='/project/RDS-FEI-InfoDynFuncStruct-RW/Leo/inference/hpc_pypet_single_target.py'
traj_dir='/project/RDS-FEI-InfoDynFuncStruct-RW/Leo/inference/trajectories/2018_04_19_00h29m12s/'
traj_filename='/project/RDS-FEI-InfoDynFuncStruct-RW/Leo/inference/trajectories/2018_04_19_00h29m12s/traj.hdf5'
file_prefix='run_00000004'
target_id=91
cd ${traj_dir}
python ${python_script_path} ${traj_dir} ${traj_filename} ${file_prefix} ${target_id}